version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - mern
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - mern

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:

networks:
  mern:
